### ISSUE TITLE
Gloss pages display wrong field choices

### ISSUE THREAD

**Issue by richardbank** [Woseseltops/signbank#102]
When user language is set to English, for all signs the same field choices are shown. For each field choice, this is the lowest available machine value (so all signs have Handedness = 1, Handshape = 5 for both hands, etc). 
When user language is set to Dutch, the sentence 'not yet translated' is shown (this is correct).
Field values are shown correctly in the search page, and searching also works as expected.

**Comment by Woseseltops** [comment]
Ah sorry, a bug I introduced last week while working on the field choices #32 , caused by the fact that fundamentally changed how and where 'human values' are retrieved. I already fixed it quietly hoping nobody had noticed, but now I see it even has its own issue. Let me know if it still pops up somewhere.
