### ISSUE TITLE
Delete Absolute Orientation fields and Movement Manner field

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#109]
AbsOriPalm, AbsOriFing, and MovMan can be deleted from the models & database, and also from the detail view, the search panel Phonology, the CSV export, field choices in Django, and .... any other place?

**Comment by Woseseltops** [comment]
Ha, finally my refactoring pays off :D. Because of all kinds of changes I made months ago, this was just a matter of removing three strings from a number of lists. I removed it from:
* The detail view
* The search view
* The CSV export (for which I discovered the headers were broken by all internationalization, so I fixed that as well in the process)
* The field choices

But not yet from the underlying database and model, because it's much handier to do that while cleaning other fields as well, as described in #114
