### ISSUE TITLE
Create a more compact view on the search page 

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#16]
- Decrease line spacing in list of search hits. Can we put them a little closer together, if only by some 20%, so that more items appear on the screen?
- Same for the search panels above the results: they can well be 5 pixels apart, rather than the current 50(?)
- Same for the search fields within a panel. The text boxes seem to dictate the height now. The font size in the text boxes should be more similar to that in the pull-down menus (10 instead of 12-14pt, it looks to me). After that, the spacing above and below the pull down menus and the text boxes can be reduced a bit.

**Comment by Woseseltops** [comment]
Done:
* I added the 'table-condensed' class to the search hits.
* Same for the search options inside the panels morphology, semantics  and phonology. It looked ugly/crammed for the other search panels.
* Some more more cleaning up to give the page a more clean look.
* I put the panels closers together.

I don't fully understand what you say about font size. It's 14px on almost the whole page, all set by a single piece of code. I can see this because everything (including the text field and the pulldown menu) shrinks when I make the number smaller. Maybe you want the text boxes smaller?

**Comment by Woseseltops** [comment]
More wishes from Onno:
* Only 10px between general search and first panel
* Space at the bottom of panels same size everywhere
* 'Phonology other' only 1 text field

**Comment by Woseseltops** [comment]
@ocrasborn Your wishes came true!

**Comment by ocrasborn** [comment]
Yes!
