### ISSUE TITLE
Batch upload videos

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#20]
- Create a batch upload function (either within SB or through an external script);
- To upload sets of lexeme videos;
- Matching video file names (without extension) to the field Annotation ID Gloss.

**Comment by Woseseltops** [comment]
After committing, I realised this won't fully work yet. To be continued :).

**Comment by Woseseltops** [comment]
https://github.com/Woseseltops/signbank/wiki/How-to-batch-upload-videos-for-signbank.science.ru.nl

**Comment by Woseseltops** [comment]
Adding the gloss numbers required my external script to have access to the Django/Signbank files, which turned out to be super-complex for a larger project like Signbank. 

After a few hours of trying various methods, I decided to do it in a completely different way, and transformed the script into a 'normal' django view. In retrospect, this is not only easier for me, but also much easier for the end users as well. Too bad it took me so long to realize this ;).

**Comment by Woseseltops** [comment]
With this last commit, I could upload the batch Onno wanted to upload today. These are the changes I made on the basis of the error:

APPLAUS > APPLAUS-A
AVONDTUUR > AVONTUUR
ALSUBLIEF > ALSTUBLIEFT

Verwijderd (=verplaatst naar mapje removed_glosses):
Appartement-B
BEDOELEN-1

**Comment by ocrasborn** [comment]
It appears that after using the batch upload script, it is no longer possible to manually change the video. The uploading works, the file name is suffixed with -1 and appears in the correct  folder, but Signbank still displays the initial video (and doesn't delete the corresponding file). When uploading a second time, it says in the edit mode "We have 2 videos for this sign." 
The example we tested is BESLUITEN-B and BESLUITEN-C, as the videos were reversed for these two (that is, they got the wrong filenames during the video editing process).

**Comment by Woseseltops** [comment]
I indeed assumed you would only upload videos that weren't on the server already. If a video is already there, do you want it to be overwritten? And if yes, is it needed to add some kind of notification for it?

**Comment by ocrasborn** [comment]
Overwriting: yes; message: only if easy to do (list the files under a heading "Overwritten files".

**Comment by Woseseltops** [comment]
This now works, including the list of overwritten files!

However, I noticed that a lot of videos are not owned by the webserver, but by @ocrasborn . If you try to overwrite these, you will get a Permission denied. This for example the AA folder:

-rw-r--r--    1 ocrasborn   wwwsignbank 144K jan  8 13:03 AANBELLEN-752.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 144K jan  8 13:03 AANBIEDEN-2439.mp4
-rw-rw----+   1 wapsignbank wwwsignbank 144K dec 12 12:36 AANBIEDEN-2439.mp4.bak
-rw-r--r--    1 ocrasborn   wwwsignbank 146K jan  8 13:03 AANDACHT-A-1201.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 167K jan  8 13:03 AANDACHT-B-2572.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 158K jan  8 13:03 AANDACHT-C-1208.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 133K jan  8 13:03 AANHALINGSTEKENS-2599.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 160K jan  8 13:03 AANHANGWAGEN-1650.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 143K jan  8 13:03 AANKLEDEN-A-384.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 143K jan  8 13:03 AANKLEDEN-B-385.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 163K jan  8 13:03 AANKLIKKEN-407.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 150K jan  8 13:03 AANKLOPPEN-895.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 152K jan  8 13:03 AANPAKKEN-1202.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 166K jan  8 13:03 AANPASSEN-2732.mp4
-rw-rw----+   1 wapsignbank wwwsignbank 7,4M feb 16 16:42 AANRANDEN-3039.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 170K jan  8 13:03 AANSLUITEN-2411.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 153K feb 11 17:37 AANTREKKEN-72.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 183K jan  8 13:03 AANVALLEN-774.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 139K jan  8 13:03 AANVALLEN-TEAMS-1985.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 143K jan  8 13:03 AANWEZIG-2359.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 128K feb 11 17:37 AAP-2859.mp4
-rw-r--r--    1 ocrasborn   wwwsignbank 161K jan  8 13:03 AARDBEI-1037.mp4
-rw-rw----+   1 wapsignbank wwwsignbank 5,8M feb 16 16:41 AARDIG-3040.mp4

I don't know how this happened (possibly some manual copypasting?), but I don't have the rights to fix it. The only solution would be to delete these videos and import them again (so it's a normal import instead of an overwrite).

**Comment by ocrasborn** [comment]
Wessel, how could we best delete them? Just remove the files on Ponyland?

**Comment by Woseseltops** [comment]
Yes... but as long as you're not overwriting videos, that's not needed. It's just so you know what's happening when you get a Permission denied during video import.

**Comment by ocrasborn** [comment]
1) I noticed that the report of correctly imported and overwritten files overlaps. That didn't match what I did the last time: the import_videos directory contained both files from the previous import (no longer removed after importing, apparently? easier if they would be, like before) and newly uploaded files. The overwritten list should not contain the newly uploaded ones, for which no video was present before.
2) When I remove all files from the folder and uploaded a new batch, the import_videos script fails: 'permission denied'. What goes wrong?

**Comment by ocrasborn** [comment]
I just noticed that in the Django Admin interface, under Videos > Sign Videos, I see a seemingly random list of 187 videos, where the batch upload has by now uploaded around 1,000 videos. Are the 187 ones only the manually uploaded ones? Perhaps good to synchronise this list with the actually available videos. (not urgent)

**Comment by Woseseltops** [comment]
>  When I remove all files from the folder and uploaded a new batch, the import_videos script fails: 'permission denied'. What goes wrong?

This is the problem is was talking above. I added a custom error message to the import_videos script for convenience, which revealed the problem:

> Failed two overwrite BOER. Maybe this file is not owned by the webserver?

The video for BOER was owned by you, so the webserver couldn't overwrite it:

<code>-rw-rw-r--    1 ocrasborn   wwwsignbank 171K jan 28 22:46 BOER-1397.mp4</code>

I removed the video, as well as EVEN-WACHTEN, and that fixed it.

For your information: in an attempt to get the script running, I also renamed FLES-A to FLES and SNAP-ER-NIETS-VAN to SNAP-ER-NIKS-VAN. It's currently stuck at EURO-A, but now I don't know what to do.

**Comment by Woseseltops** [comment]
> no longer removed after importing

You're right, I forget to re-add that. It's back now!

> The overwritten list should not contain the newly uploaded ones, for which no video was present before.

Sounds like a bug. Weird, for me it worked. Before I spend too much time trying to reproduce the bug: as soon as this pops up again, could you post the text of the page here? So I can see which videos have the problem.

**Comment by Woseseltops** [comment]
> In the Django Admin interface [...] I see a seemingly random list of 187 videos Are the 187 ones only the manually uploaded ones?

That would be my guess. I wasn't really aware of the fact that there is 'video' model in the Django admin, so I never linked my import_videos script to it. Two solutions:
1. Hide it from the Django admin.
2. Create a script that will link all existing videos to the admin, and add this link action to the import_videos script as well.

If you pick solution 2, I think a separate issue would be convenient :).

**Comment by ocrasborn** [comment]
As to the Django admin: propose to leave it as is, for the moment. Very low priority :-)
