### ISSUE TITLE
Change field 'Compound of' to a table

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#35]
1. Remove (or do not display) fields 'Morphology' and 'Compound of' (not used in NGT data set now). (They're under Basic Properties in the detail view now.)
2. Add a block similar to Relations to Other/Foreign Signs, in a panel called Morphology, containing two columns:
a) Type  --> a value from the following list: "Compound part 1, Compound part 2, Compound part 3, Compound part 4, Classifier handshape, Letter handshape, Number handshape, Symbolic handshape, Symbolic location" [list editable in Field Choices in Django]
b) Morpheme --> a reference to an existing lexical entry
The end of each row should include a link "(Show)", as in the Relations to Other Signs part.
The block 'Morphology' should be second in the detail / search views: after Basic Properties, before Phonology.
3. Add to search interface

**Comment by Woseseltops** [comment]
Done:

* Added a morphology data model
* Change the database (which means backing up and downloading the whole thing, adding the field locally, making sure it doesn't freak out about this new field it didn't know about before, uploading it again)
* Added morphology to the Django admin
* Added a morphology tab to the website, filled with data from the database
* Added front-end functionality to make the morphology editable 
* Added front-end functionality to add new morphology
* Added front-end functionality to remove morphology
* Made back-end code that listens to all of that

I used existing code as much as possible, but the requirements for this functionality were too different for things to go slowly and smoothly - that's why it took so long ;).

To do:
* Add morphology to the export and import functionality
* Add morphology to the search functionality

**Comment by Woseseltops** [comment]
I just discovered I have a blocking question for both items on the to do list for this issue:

* For the export and import: the other more complex fields are not in the export (yet). Should morphology be skipped as well? And if not, how should it look?
* For the search functionality: how do you want to search for morphology? Proposal: a separate field 'Search by Morphology', that contains two fields. 'Search by morpheme' lets you type in the text of a gloss, and filters the results for glosses that have morphological relation to this gloss, and 'Type of morpheme' lets you pick a type from a list, and filters the results for glosses that contain the type of morpheme.

**Comment by ocrasborn** [comment]
1) For the export: we should like to have all these complex fields in the export+import routines, but let's create a separate issue for that and assign it a lower priority.
2) For the search: suggestion is good.

**Comment by Woseseltops** [comment]
Added morphology search panel as well

**Comment by ocrasborn** [comment]
Field 'Compound of' removed from search page
