### ISSUE TITLE
Add field Keywords/Translations to search results list

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#53]
- Make it the 3rd column, following "Annotation ID Gloss: English"
- Column header: "Translations"

**Comment by ocrasborn** [comment]
Consider making the whole site layout some 20% wider. Not sure what screen resolution constrained the present width (1140px), but even on my Macbook air (1440px) there's plenty of white space on the side. Perhaps try out 1300px first for a while, and see how that impacts the rest of the layout?

**Comment by Woseseltops** [comment]
It works, but I would like to give this some more time, because the way I did it now feels really dirty, and I think I can come up with a cleaner and more elegant solution.

> Consider making the whole site layout some 20% wider.

My personal preference would be not do do this, because:
* As far as I can see, everything fits in the current layout.
* I think that websites that are are too wide are uncomfortable to read. See http://ux.stackexchange.com/questions/53506/why-we-dont-use-wider-interfaces-on-wide-screens . That is, I don't think the current layout has so much of white space on the sides because of screen resolution constraints, but because of usability.

It's only a slight preference, though :)

**Comment by ocrasborn** [comment]
More time OK :-) -- and while you're at it, could you make the keywords comma separated?

**Comment by Woseseltops** [comment]
Done. The commas were harder then expected, because there should only be one BETWEEN keywords, not after every keyword.
