### ISSUE TITLE
Tag list is not read from Django Tags

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#67]
- The menu with the list of possible tags (in edit mode) includes a list (now 3 'workflow' items) that are hard-coded, rather than read from the Tag list edited in Django's admin.
- The Django tag list doesn't allow spaces in items, is it possible to enable that?

**Comment by Woseseltops** [comment]
This took me quite a while to figure out, but it turns out there is a code library called *tagging* that is used for this. This must have sped up Steves development greatly, but it actually complicates things for us, as it locks away most tag-related code for customization.

The first point was relatively easy; the choices are now linked to the Django admin similar to how the field choices are. Like with the field choices, you have to visit http://signbank.science.ru.nl/reload_signbank/ to update the whole system. By the way, linking the tagging system to the admin seems to be supported by the tagging library, so I don't really understand why Steve didn't use it that way. Until now, the choices could be edited from the settings file.

The second point, with the spaces, is a lot harder, as the whole library seems to be built around the assumption that all tags will be single words. On Stack Overflow I find more developers asking questions about it, and the answer seems to be that you have to edit the library yourself. I really dislike that solution, as that would mean that everybody who wants to use our version of signbank also needs the custom-edited version of the library. Instead, I added that all underscores in the admin are shown as spaces on the website. For example, there is a tag 'Wessel_is_working_on_this', which is shown as 'Wessel is working on this' on the site. Good enough?

**Comment by ocrasborn** [comment]
Good enough :-)

**Comment by ocrasborn** [comment]
...though in the detail view it still appears as an underscore

**Comment by Woseseltops** [comment]
If with detail view you mean the search results... not any longer :)

**Comment by ocrasborn** [comment]
Man you're quick!
Could you resize the columns in the search results, making tags, say, 2.8 times as big and reducing the Translation Equivalents accordingly?

**Comment by Woseseltops** [comment]
It took me quite a while to realize that the Tags box becomes really small when you search for things with a lot of translations. In my test search the tag box was really large, so I wondered why you want to fill the whole page with tags :P. 

Anyway, I've now given the tags column a fixed size of 255px. Most of this space is automatically 'taken' from the translation column.
