### ISSUE TITLE
Create a Django permission for displaying the 'Update ECV' button

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#68]
Aarthy was going to allow only Editors and Publishers to see the button, but there's no permission yet that she can use. If she fixes it in another way, it would still be good to have a separate permission that we can assign to users and groups.

**Comment by Woseseltops** [comment]
Done! For later reference, this is how I did it:
* Customs permissions for models can be added to the 'meta' method of the models; from that point on, they can succesfully be used inside the code, but won't show up in the Django admin.
* To make the new custom permissions show up in the admin, a 'manage.py syncdb --all' is needed. This is not possible inside the production environment, because Django locks the database file. To fix that, I made a local clone of Signbank, copied the database into it, ran the syndb, and then copied the database back to the production environment
