### ISSUE TITLE
Redirect user to search page after reloading signbank... 

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#77]
... after, say, 3 seconds of showing the 'OK' message. (That is, after i do http://signbank.science.ru.nl/reload_signbank/ in the process of adding field choices, https://github.com/Woseseltops/signbank/wiki/How-to-add-new-field-choices-to-Signbank)

(There was another situation where a blank page with 'OK' appears, i seem to remember, but forgot where/when. Please do the same there.)

**Comment by Woseseltops** [comment]
That would be a little bit inconvenient for me, as I always have this page open in a tab, and I refresh it all the time to see the result of my edits. Two alternative solutions:
* The 'OK' page is turned into a nice looking Signbank page that says 'Reload successful'
* The reload functionality gets an argument 'redirect' that defines whether and to which page the user will be redirected. We can even make the search page the default, so that
  * _reload_signbank_ goes to the search page, as you propose
  * _reload_signbank?redirect=false only_ shows 'OK', like I prefer to use it

**Comment by ocrasborn** [comment]
Let's keep it simple (for you) -- what will cost less time?
I'd also be happy with a third option: adding two hyperlinks below 'OK', one leading to the Home, one leading to Search (using just those two words).

**Comment by Woseseltops** [comment]
Picked a solution that mixes my first option and your answer to it.
