### ISSUE TITLE
Signbank keeps reloading

### ISSUE THREAD

**Issue by richardbank** [Woseseltops/signbank#80]
Every pages on the website refreshes every second or so. Searching is impossible, videos are (broken off and) repeated -  unless you press escape after each page load. This only happens after login. Behaviour is observed in Chrome and FF on Win7, Chrome, FF and IE11 on Win8.1, and Chrome, FF and Safari on Mac. 
In IE8, signbank doesn't work at all (but i don't know if that is new behaviour).

**Comment by richardbank** [comment]
Addition to the previous post: the reload-cycle takes a lot longer on large pages (e.g. Search) than on small pages (e.g. the Home page), suggesting something with a script on the bottom of the page.

**Comment by Woseseltops** [comment]
Solved together with @ocrasborn . Problem turned out to be that the reloading pages were caused by the absence of a user profile. A 'user profile' is a Django thingy I recently activated to save language preferences. The profiles are automatically added to (1) new accounts and (2) accounts hwere the language is set manually in the admin (= my account). The remaining exisiting accounts have the problem when logged in.

The solution is to set the language manually in the admin for existing accounts. You can see if you succeeded by checking the new database 'user profiles' in the admin. You can also check the 'Users' database. If it says 'User Profile: #1' at the bottom of a particular user page, there is no profile yet.
