### ISSUE TITLE
Replace 'No Value Set' by dash (-)

### ISSUE THREAD

**Issue by ocrasborn** [Woseseltops/signbank#9]
Empty fields in the detail views now appear as 'No Value Set', making it hard to distinguish empty from filled fields. Better replace by '-' (or just nothing?).

**Comment by Woseseltops** [comment]
Mostly done!

I thought this would be a quick one, but it turned out Steve didn't use standard Django functionality for this, but some very well hidden self-backed piece of code. I finally found and replaced it, and now it's working for most fields.

Not for all, though; this reveiled that some choice fields are not using the dynamic choices yet, which I think already proves that this improvement is a good one :).

**Comment by Woseseltops** [comment]
Forgot to link this commit: https://github.com/Woseseltops/signbank/commit/b734551de6a932ceeabed5ea01931dc57f7d1d11

**Comment by Woseseltops** [comment]
Done.
