### ISSUE TITLE
Import CSV function is broken

### ISSUE THREAD

**Issue by richardbank** [Woseseltops/signbank#92]
When I try to import a CSV with updated phonological information, the preview page says:

>The following changes were detected:
>* For , changes from () to ().
>* For , changes from () to ().
>* For , changes from () to ().
>* ... (repeat 2000+ times)

From the source code of the page, I infer that under the hood everything still works:

`<li>For , <em></em> changes from  () to  ().</li>`
`<input type="hidden" name="407.locVirtObj"  value="Aanklikken">`

`<li>For , <em></em> changes from  () to  ().</li>`
`<input type="hidden" name="407.locprim"  value="3">`

(the values are for the 'Virtual Object'- and 'Location'-columns that are imported.)
(this doesn't seem language related, changing my default language didn't help :-)

**Comment by Woseseltops** [comment]
Fixed! As you already discovered (good find, by the way), this was only a front-end display issue; the mechanism still works. The values were not displayed because they were inside a blocktrans tag (which means: this string should have translations), but the variables/placeholders were not defined. Apparently, this is needed for blocktrans tags.
